<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Melanchall.DryWetMidi" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quizizzo.GameContracts\Quizizzo.GameContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\*.mid" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Quizizzo.Games.VoiceChoon</RootNamespace>
  </PropertyGroup>

</Project>
