<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Quizizzo.GameContracts\Quizizzo.GameContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/estimate-questions.json"
                      LogicalName="Quizizzo.Games.Estimate.Assets.estimate-questions.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
