<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Quizizzo_Web-135344d6-2473-4d52-86f6-3da834c984db</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quizizzo.Application\Quizizzo.Application.csproj" />
    <ProjectReference Include="..\Quizizzo.Infrastructure\Quizizzo.Infrastructure.csproj" />
    <ProjectReference Include="..\Quizizzo.GameEngine\Quizizzo.GameEngine.csproj" />
    <ProjectReference Include="..\Quizizzo.Games.Estimate\Quizizzo.Games.Estimate.csproj" />
    <ProjectReference Include="..\Quizizzo.Games.MajorityRules\Quizizzo.Games.MajorityRules.csproj" />
    <ProjectReference Include="..\Quizizzo.Games.Bullshit\Quizizzo.Games.Bullshit.csproj" />
    <ProjectReference Include="..\Quizizzo.Games.AniMates\Quizizzo.Games.AniMates.csproj" />
  </ItemGroup>

</Project>
